#!/usr/bin/env bash

case "$1" in
    enable)
	# Enable services
	systemctl -q enable 01-usec.timer &&
	systemctl -q enable 02-msec.timer &&
	systemctl -q enable 03-seconds.timer &&
	systemctl -q enable 04-minutes.timer &&
	systemctl -q enable 05-hours.timer &&
	systemctl -q enable 06-days.timer &&
	systemctl -q enable 07-weeks.timer &&
	systemctl -q enable 08-months.timer &&
	systemctl -q enable 09-quarters.timer &&
	systemctl -q enable 10-sixmonths.timer &&
	systemctl -q enable 11-years.timer &&
	echo -e "\nServices: enabled."
    ;;

    disable)
	# Disable services
	systemctl -q disable 01-usec.timer &&
	systemctl -q disable 02-msec.timer &&
	systemctl -q disable 03-seconds.timer &&
	systemctl -q disable 04-minutes.timer &&
	systemctl -q disable 05-hours.timer &&
	systemctl -q disable 06-days.timer &&
	systemctl -q disable 07-weeks.timer &&
	systemctl -q disable 08-months.timer &&
	systemctl -q disable 09-quarters.timer &&
	systemctl -q disable 10-sixmonths.timer &&
	systemctl -q disable 11-years.timer &&
	echo -e "\nServices: disabled."
    ;;

    start)
	# Start services
	systemctl -q start 01-usec.timer &&
	systemctl -q start 02-msec.timer &&
	systemctl -q start 03-seconds.timer &&
	systemctl -q start 04-minutes.timer &&
	systemctl -q start 05-hours.timer &&
	systemctl -q start 06-days.timer &&
	systemctl -q start 07-weeks.timer &&
	systemctl -q start 08-months.timer &&
	systemctl -q start 09-quarters.timer &&
	systemctl -q start 10-sixmonths.timer &&
	systemctl -q start 11-years.timer &&
	echo -e "\nServices: started."
    ;;

    stop)
	# Stop services
	systemctl -q stop 01-usec.timer &&
	systemctl -q stop 02-msec.timer &&
	systemctl -q stop 03-seconds.timer &&
	systemctl -q stop 04-minutes.timer &&
	systemctl -q stop 05-hours.timer &&
	systemctl -q stop 06-days.timer &&
	systemctl -q stop 07-weeks.timer &&
	systemctl -q stop 08-months.timer &&
	systemctl -q stop 09-quarters.timer &&
	systemctl -q stop 10-sixmonths.timer &&
	systemctl -q stop 11-years.timer &&
	echo -e "\nServices: stopped."
    ;;

    status)
	# Show timers
	systemctl list-timers --all
    ;;

    *)
	echo "Usage: timers.sh {enable|disable|start|stop|status}"
	exit 1
    ;;

esac

exit 0
