#!/usr/bin/env bash

case "$1" in
    enable)
	# Enable services
	sudo systemctl -q enable 01-minutely.timer &&
	sudo systemctl -q enable 02-hourly.timer &&
	sudo systemctl -q enable 03-daily.timer &&
	sudo systemctl -q enable 04-weekly.timer &&
	sudo systemctl -q enable 05-monthly.timer &&
	sudo systemctl -q enable 06-quarterly.timer &&
	sudo systemctl -q enable 07-semiannually.timer &&
	sudo systemctl -q enable 08-yearly.timer &&
	echo -e "\nServices: enabled."
    ;;

    disable)
	# Disable services
	sudo systemctl -q disable 01-minutely.timer &&
	sudo systemctl -q disable 02-hourly.timer &&
	sudo systemctl -q disable 03-daily.timer &&
	sudo systemctl -q disable 04-weekly.timer &&
	sudo systemctl -q disable 05-monthly.timer &&
	sudo systemctl -q disable 06-quarterly.timer &&
	sudo systemctl -q disable 07-semiannually.timer &&
	sudo systemctl -q disable 08-yearly.timer &&
	echo -e "\nServices: disabled."
    ;;

    start)
	# Start services
	sudo systemctl -q start 01-minutely.timer &&
	sudo systemctl -q start 02-hourly.timer &&
	sudo systemctl -q start 03-daily.timer &&
	sudo systemctl -q start 04-weekly.timer &&
	sudo systemctl -q start 05-monthly.timer &&
	sudo systemctl -q start 06-quarterly.timer &&
	sudo systemctl -q start 07-semiannually.timer &&
	sudo systemctl -q start 08-yearly.timer &&
	echo -e "\nServices: started."
    ;;

    stop)
	# Stop services
	sudo systemctl -q stop 01-minutely.timer &&
	sudo systemctl -q stop 02-hourly.timer &&
	sudo systemctl -q stop 03-daily.timer &&
	sudo systemctl -q stop 04-weekly.timer &&
	sudo systemctl -q stop 05-monthly.timer &&
	sudo systemctl -q stop 06-quarterly.timer &&
	sudo systemctl -q stop 07-semiannually.timer &&
	sudo systemctl -q stop 08-yearly.timer &&
	echo -e "\nServices: stopped."
    ;;

    status)
	# Show timers
	systemctl list-timers --all
    ;;

    *)
	echo "Usage: timers.sh {enable|disable|start|stop|status}"
	exit 1
    ;;

esac

exit 0
